### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by sberryman** [Rudrabha/Lip2Wav#11]
Excellent work and I love that you used a synthesized voice for the project video. I spent a lot of time on Corentin's Real Time Voice Cloning project and noticed you used some of his code as your base.

Just wondering what you plan on doing from this point with the project. Are you going to continue working on it or have you already moved on to new projects?

**Comment by Rudrabha** [comment]
Hello,
Thanks a lot for your interest in our work. Though we do have plans to improve this work later, we are not working on the project at the moment. This work was done around October last year and since then we have moved on to a couple of other projects which are under review at the moment.

**Comment by sberryman** [comment]
@Rudrabha, thanks for the quick reply. Anything you can share at the moment? I'm really looking forward to see what you do next!

Are you still working on a cross between the vision and audio domain? I would love to see a GAN similar to [talking heads](https://arxiv.org/pdf/1905.08233.pdf) which has accurate lip sync to synthetic audio. 

For context, I started training a talking heads model based on this [code](https://github.com/grey-eye/talking-heads).
It has been training for about 44 hours and is on ~Epoch 5.4.

The model has just started learning about baseball caps, glasses and facial hair. Skin is still very smooth and it struggles to capture facial aging. Nose shape is progressing as well as open and closed eye lids. Eye gaze seems be for straight forward in all the generated images.

## Example 1:
![image](https://user-images.githubusercontent.com/324437/87187588-410bbc00-c2a2-11ea-8241-5db80841a1bb.png)

## Example 2:
![Screenshot-20200710112120-379x536](https://user-images.githubusercontent.com/324437/87187626-541e8c00-c2a2-11ea-82fd-ab1fb39b850a.png)

## Example 3:
![Screenshot-20200710111120-372x500](https://user-images.githubusercontent.com/324437/87187629-54b72280-c2a2-11ea-9ec5-06a98b068d27.png)

## Example 4:
![Screenshot-20200709125514-380x546](https://user-images.githubusercontent.com/324437/87187646-5da7f400-c2a2-11ea-90fe-35aec0ef8b34.png)

**Comment by Rudrabha** [comment]
You can check out our work that was published in ACM Multimedia [here](https://github.com/Rudrabha/LipGAN). For any related query/comment on the lipsync project, please open an issue in the LipGAN repository.

**Comment by sberryman** [comment]
Well look at that, you already built it! Project video is impressive, thanks for pointing me to the LipGAN project.
