### ISSUE TITLE
Bug in multispeaker branch

### ISSUE THREAD

**Issue by miraodasilva** [Rudrabha/Lip2Wav#13]
Hi,

I came across a bug when preprocessing LRW, where ffmpeg fails silently. I'm pretty sure this line https://github.com/Rudrabha/Lip2Wav/blob/a5835ffbaf8d0e13e4ea3b2c391618ffd9cc26bd/preprocess.py#L63 should be changed to `	command = template2.format(vfile, wavpath) `. This is what worked for me.

By the way, are you planning to release test samples/checkpoints for GRID/TCD-TIMIT. This would be great so that we can compare accurately with your work.

Thanks a lot in advance!

**Comment by Rudrabha** [comment]
Hello,

Thanks for pointing the mistake out. I have corrected it. We do not plan to release the models for GRID and TIMIT at the moment. If we do so, we will definitely notify you.
