### ISSUE TITLE
Encountered ValueError  during training

### ISSUE THREAD

**Issue by ZzZzEnG** [Rudrabha/Lip2Wav#14]
Hi! 
It's really a nice work! But I'm facing a problem while training:
![image](https://user-images.githubusercontent.com/32928342/87774778-9a9e5880-c857-11ea-97b3-d260e37a6f74.png)
When training train.py with the command: python train.py chem --data_root Dataset/chem/ --preset synthesizer/presets/chem.json, it occurs to the ValueError: 'Multi-valued hyperparameters cannot be empty: all_test_images.' I can't find the hyperparameter throughout the code that named 'all_test_images'. 
Am I Assigning the wrong values of 'name of run'? Is it a directory like '/Dataset/chem' or the random name that we gave such as 'chem'? I have tried the training with different 'name' values, such as 'chem', '/Dataset/chem' or '/Dataset/chem/preprocessed/', it didn't work, still report the same error.
Looking forward to your answer! Thanks a lot!

**Comment by prajwalkr** [comment]
Hello

Can you please print the variable `all_test_images' and run your command and paste the printed output here? 

I am suspecting that the data_root path specified is incorrect. That is, the script was unable to find test images. So, could you also do an `ls` inside the `Dataset` folder and the `Dataset/chem` folder and paste it here?

**Comment by ZzZzEnG** [comment]
Thanks for your reply!
I'm afraid that the variable `all_test_images' is not defined in the code, it appeared out of the blue.
![image](https://user-images.githubusercontent.com/32928342/87781221-e0ace980-c862-11ea-87d0-08a462df12a7.png)

The contents of Dataset and Dataset/chem are as below:
![image](https://user-images.githubusercontent.com/32928342/87780118-9d517b80-c860-11ea-828c-a9ac9eb9dc88.png)

**Comment by prajwalkr** [comment]
> I'm afraid that the variable `all_test_images' is not defined in the code, it appeared out of the blue.

https://github.com/Rudrabha/Lip2Wav/blob/5247a82aef611059fb8c176422e8bbd64f5d0bef/train.py#L19

Please also verify if there are images in the subfolders of the preprocessed folder.

**Comment by ZzZzEnG** [comment]
Ohhh! I noticed that the code was downloaded in June 2nd, and now I have downloaded the latest version, there's no more question. Thanks for your patience again!!!
