### ISSUE TITLE
Lip2Wav dataset not available

### ISSUE THREAD

**Issue by tomguluson92** [Rudrabha/Lip2Wav#2]
Hi,
     I am really happy to see your pioneering work! And I am wondering whether can I download the Lip2Wav dataset? (the project website do not offer the URL).
    Really appreciate it, thank you~

**Comment by Rudrabha** [comment]
We have just added a dataset for one speaker with its pre-trained model. I am leaving this issue open till we release all of them.

**Comment by prajwalkr** [comment]
The dataset is present in the folder of this repo. Three out of five speakers have been released. Two more speakers will be released at a later time.
