### ISSUE TITLE
training and test split for GRID and TCD-TIMIT

### ISSUE THREAD

**Issue by WillQuCD** [Rudrabha/Lip2Wav#6]
Nice work!
Could you please share the train, validation and unseen test splits for GRID and TCD-TIMIT used in your paper? 
The unseen means unseen speakers or unseen sentences?
Do you also train one model for each speaker?

Thanks!

**Comment by prajwalkr** [comment]
"Unseen" means unseen sentences (not unseen speakers) because, models trained on GRID and TIMIT are speaker-specific, so one model for each speaker.

**Comment by enhuiz** [comment]
May the author share the specific split for fair comparisons of future works for the GRID and TCD-TIMIT dataset?  Many thanks.
