### ISSUE TITLE
About teacher force

### ISSUE THREAD

**Issue by MontaEllis** [Rudrabha/Lip2Wav#7]
Hello, nvidia tacotron2 uses teacher-forceing, I was wondering where it is in your code? Can you help me?

**Comment by Rudrabha** [comment]
Please check this [line](https://github.com/Rudrabha/Lip2Wav/blob/a524a9cb9d41342f77dd788b72a24c6adf6dcbc0/synthesizer/models/helpers.py#L115) in the code for teacher forcing.
