### ISSUE TITLE
Dataset Downloading Error

### ISSUE THREAD

**Issue by AvivSham** [Rudrabha/Lip2Wav#8]
Hi All,
Thank you very much for this project!
I tried to run `sh download_speaker.sh Dataset/chem` but it seems there is a problem downloading the videos from youtube.
This is the error I'm getting:
```
Downloading Train set of chem
[youtube] rvPHWWNYC0I: Downloading webpage
[youtube] rvPHWWNYC0I: Downloading video info webpage
ERROR: rvPHWWNYC0I: YouTube said: This video is unavailable.
```
which stops the training set download process, the same happens for val/test sets. I tried to check if it is possible to see the video directly from Youtube's website and indeed it is possible (so the video exists).

Thank you in advance.

**Comment by prajwalkr** [comment]
Please update your youtube-dl package and try again:

`pip install --upgrade youtube-dl`

**Comment by AvivSham** [comment]
I have done the following:
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install youtube-dl
```
didn't work for me :/

**Comment by prajwalkr** [comment]
> Please update your youtube-dl package and try again:
> 
> `pip install --upgrade youtube-dl`

Please do this and re-open the issue if it does not solve the issue.

**Comment by Pranav122002** [comment]
@prajwalkr @Rudrabha @AvivSham Can you tell how to run this command in windows CMD terminal ? as sh is for linux.
